build:
    environment:
        php:
            version: 5.6
build:
    tests:
        override:
            -
                command: 'phpunit --coverage-clover=embeddables-coverage'
                coverage:
                    file: 'embeddables-coverage'
                    format: 'clover'